books = [
    {
        "id": 0,
        "title": "War and Peace",
        "language": "Russian",
        "year": 1869,
        "buy_price": 12.43,
        "sell_price": 24.99,
        "path": "storage/sz1twealoq.pdf",
    },
    {
        "id": 1,
        "title": "Don Quixote",
        "language": "Spanish",
        "year": 1605,
        "buy_price": 7.13,
        "sell_price": 15.99,
        "path": "storage/0r0ewpsm15.pdf",
    },
    {
        "id": 2,
        "title": "The Great Gatsby",
        "language": "English",
        "year": 1925,
        "buy_price": 10.12,
        "sell_price": 19.99,
        "path": "storage/zb20ww7jan.pdf",
    },
    {
        "id": 3,
        "title": "Les Misérables",
        "language": "French",
        "year": 1862,
        "buy_price": 8.94,
        "sell_price": 12.99,
        "path": "storage/1nt3tsi2vb.pdf",
    },
    {
        "id": 4,
        "title": "Crime and Punishment",
        "language": "Russian",
        "year": 1866,
        "buy_price": 14.67,
        "sell_price": 29.99,
        "path": "storage/tpz2rzyryc.pdf",
    },
]
